version: 2
jobs:
  build:
    working_directory: /tictag
    docker:
      - image: clojure:lein-2.7.1
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/tictag.jar
          destination: uberjar
      - deploy:
          name: Deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then bin/deploy; fi
