version: 2
jobs:
  build:
    working_directory: /root/tictag
    docker:
      - image: clojure:lein-2.7.1
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - /root/.m2
            - /root/.lein
          key: << checksum "project.clj" >>
      - run: |
          apt-get update && apt-get install --no-install-recommends -y g++ build-essential
          cd /tmp
          git clone --depth=1 https://github.com/sass/libsass.git
          git clone --depth=1 https://github.com/sass/sassc.git
          export SASS_LIBSASS_PATH=/tmp/libsass
          cd /tmp/sassc; make install
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/tictag.jar
          destination: uberjar
      - add_ssh_keys
      - deploy:
          name: Deploy master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then bin/deploy; fi
